version: 0.2

phases:
  install:
    commands:
      - echo "Installing..."
  build:
    commands:
      - echo "Build step skipped."
artifacts:
  files:
    - app/**/*
    - appspec.yml
    - scripts/restart_httpd.sh

